version: '3.4'

services:
  bphogent:
    image: bphogent
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 5000:80
    # environment:
    #   - ACCESS_TOKEN=${ACCESS_TOKEN}
    #   - DB_NAME=${DB_NAME}
    #   - DB_NAME_PROD=${DB_NAME_PROD}
    #   - DB_HOST=${DB_HOST}
    # env_file: .env
